apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.3.3"
  interval: 1h0m0s
  releaseName: kyverno
  targetNamespace: kyverno
  values:
    admissionController:
      clusterRole:
        extraResources:
         - apiGroups:
           - ''
           resources:
           - secrets
           verbs:
           - create
           - update
           - delete
           - list
           - get
    backgroundController:
      clusterRole:
        extraResources:
         - apiGroups:
           - ''
           resources:
           - secrets
           verbs:
           - create
           - update
           - delete
           - patch
    cleanupController:
      clusterRole:
        extraResources:
         - apiGroups:
           - ''
           resources:
           - secrets
           verbs:
           - delete
           - list
           - watch
    reportsController:
      clusterRole:
        extraResources:
         - apiGroups:
           - ''
           resources:
           - secrets
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: kyverno-policies
#   namespace: flux-system
# spec:
#   chart:
#     spec:
#       chart: kyverno-policies
#       sourceRef:
#         kind: HelmRepository
#         name: kyverno
#       version: "3.3.1"
#   interval: 1h0m0s
#   releaseName: kyverno-policies
#   targetNamespace: kyverno