# https://taskfile.dev
version: '3'

dotenv: ['.env', '{{.HOME}}/.env']

env:
  REPO_NAME: k3s-ai-platform
  GITHUB_USER: lreimer
  GITHUB_TOKEN:
  
vars: {}

tasks:
  default:
    desc: If running only "task" print all available tasks
    cmd: task --list-all
    silent: true

  brew:
    desc: Install tool dependencies with brew
    internal: true
    run: once
    platforms: [darwin, linux]
    cmd: brew bundle --no-lock --verbose
    status:
      - brew bundle check --verbose

  bootstrap:
    desc: Bootstrap Flux
    silent: true
    requires:
      vars: [GITHUB_USER, GITHUB_TOKEN, REPO_NAME]
    cmd: | 
      flux bootstrap github \
        --owner={{.GITHUB_USER}} \
        --repository={{.REPO_NAME}} \
        --branch=main \
        --path=./clusters/{{.REPO_NAME}} \
        --components-extra=image-reflector-controller,image-automation-controller \
        --read-write-key \
        --personal

  reconcile:
    desc: Reconcile flux-system
    silent: true
    cmd: flux reconcile source git flux-system

