apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weaviate-ingress
  namespace: weaviate
spec:
  rules:
  - host: weaviate.127.0.0.1.sslip.io
    http:
      paths:
      - backend:
          service:
            name: weaviate
            port:
              number: 80
        path: /
        pathType: Prefix