apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      version: "4.0.0"
  interval: 1h0m0s
  releaseName: jupyterhub
  targetNamespace: jupyterhub
  values:
    proxy:
      service:
        type: NodePort

    ingress:
      enabled: false
      hosts:
        - host: jupyterhub.127.0.0.1.sslip.io
